export interface Resource {
  id: number;
  title: string;
  description: string;
  type: string;
  exam: string;
  iconColor: string;
  iconBg: string;
  downloadUrl: string;
  sourceUrl: string;
  fileSize: string;
  downloads: number;
  tags: string[];
  year?: number;
}

export const resourcesData: Resource[] = [
  {
    id: 1,
    title: "UPSC CSE Prelims Previous Year Papers 2013–2024",
    description: "Complete collection of UPSC Civil Services Preliminary Examination question papers with official answer keys. Covers General Studies Paper 1 & CSAT.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "45 MB",
    downloads: 182000,
    tags: ["upsc", "civil services", "prelims", "question papers"],
    year: 2024,
  },
  {
    id: 2,
    title: "SSC CGL Complete Syllabus & Exam Pattern 2024–25",
    description: "Official SSC CGL syllabus for Tier 1, 2, 3 and 4 with topic-wise weightage, marking scheme, and exam pattern changes for 2024–25 cycle.",
    type: "syllabus",
    exam: "SSC CGL",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://ssc.gov.in/Examination/Syllabus",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "2.1 MB",
    downloads: 94000,
    tags: ["ssc", "cgl", "syllabus", "tier 1", "tier 2"],
    year: 2024,
  },
  {
    id: 3,
    title: "IBPS PO Mock Test Series – 25 Full-Length Tests",
    description: "Free mock tests for IBPS PO Prelims and Mains covering Reasoning Ability, Quantitative Aptitude, English Language, General Awareness and Professional Knowledge.",
    type: "mock-tests",
    exam: "IBPS PO",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://www.ibps.in/",
    sourceUrl: "https://www.ibps.in",
    fileSize: "Online",
    downloads: 76000,
    tags: ["ibps", "po", "mock test", "banking", "prelims"],
    year: 2024,
  },
  {
    id: 4,
    title: "RRB NTPC Previous Year Papers 2016–2024",
    description: "All Railway Recruitment Board NTPC question papers from 2016 to 2024, categorised by phase and shift, with detailed solutions.",
    type: "previous-papers",
    exam: "RRB NTPC",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://www.rrbcdg.gov.in/",
    sourceUrl: "https://indianrailways.gov.in",
    fileSize: "32 MB",
    downloads: 128000,
    tags: ["rrb", "ntpc", "railway", "previous papers"],
    year: 2024,
  },
  {
    id: 5,
    title: "NEET UG Biology Notes – NCERT Topicwise",
    description: "Comprehensive NCERT-based Biology notes for NEET UG preparation covering Botany and Zoology with diagrams, mnemonics and important questions.",
    type: "study-notes",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://ncert.nic.in/textbook.php",
    sourceUrl: "https://ncert.nic.in",
    fileSize: "18 MB",
    downloads: 211000,
    tags: ["neet", "biology", "ncert", "botany", "zoology"],
    year: 2024,
  },
  {
    id: 6,
    title: "JEE Main Mathematics Formula Sheet",
    description: "All essential formulas for JEE Main Mathematics — Calculus, Algebra, Trigonometry, Coordinate Geometry, Probability and Vectors in one sheet.",
    type: "study-notes",
    exam: "JEE Main",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeemain.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "5 MB",
    downloads: 163000,
    tags: ["jee", "mathematics", "formula", "calculus", "algebra"],
    year: 2024,
  },
  {
    id: 7,
    title: "SBI PO Reasoning Ability – Topic-wise Practice Sets",
    description: "600+ practice questions for SBI PO Reasoning Ability covering Puzzles, Seating Arrangement, Syllogism, Blood Relations, Coding-Decoding and more.",
    type: "mock-tests",
    exam: "SBI PO",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://sbi.co.in/web/careers",
    sourceUrl: "https://sbi.co.in",
    fileSize: "12 MB",
    downloads: 89000,
    tags: ["sbi", "po", "reasoning", "puzzles", "practice"],
    year: 2024,
  },
  {
    id: 8,
    title: "UPSC Mains GS Paper 1 – 15 Years Solved Papers",
    description: "Solved UPSC Mains General Studies Paper 1 (History, Geography, Society) from 2010 to 2024 with model answers and examiner's comments.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "28 MB",
    downloads: 97000,
    tags: ["upsc", "mains", "gs paper 1", "history", "geography"],
    year: 2024,
  },
  {
    id: 9,
    title: "SSC CHSL Syllabus & Tier-Wise Pattern 2024",
    description: "Complete SSC Combined Higher Secondary Level exam syllabus covering Tier 1 (CBT), Tier 2 (Descriptive), Tier 3 (Skill Test) with score breakdown.",
    type: "syllabus",
    exam: "SSC CHSL",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://ssc.gov.in/Examination/Syllabus",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "1.8 MB",
    downloads: 58000,
    tags: ["ssc", "chsl", "syllabus", "tier 1", "pattern"],
    year: 2024,
  },
  {
    id: 10,
    title: "IBPS Clerk Quantitative Aptitude Video Lectures",
    description: "50+ hours of free video lectures for IBPS Clerk Quantitative Aptitude covering Number System, Percentage, SI/CI, Speed-Distance-Time and Data Interpretation.",
    type: "video-lectures",
    exam: "IBPS Clerk",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://www.youtube.com/results?search_query=ibps+clerk+quantitative+aptitude",
    sourceUrl: "https://youtube.com",
    fileSize: "Online",
    downloads: 142000,
    tags: ["ibps", "clerk", "quant", "video", "number system"],
    year: 2024,
  },
  {
    id: 11,
    title: "Current Affairs Monthly Digest – March 2025",
    description: "Comprehensive monthly current affairs covering National, International, Economy, Sports, Awards, Science & Technology for all government exams.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "8 MB",
    downloads: 201000,
    tags: ["current affairs", "monthly", "national", "international", "sports"],
    year: 2025,
  },
  {
    id: 12,
    title: "NEET UG Physics – 20 Years Chapterwise Questions",
    description: "Chapterwise collection of NEET Physics questions from 2005 to 2024 with step-by-step solutions, covering Mechanics, Thermodynamics, Optics, Electrodynamics.",
    type: "previous-papers",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://neet.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "22 MB",
    downloads: 176000,
    tags: ["neet", "physics", "chapterwise", "mechanics", "optics"],
    year: 2024,
  },
  {
    id: 13,
    title: "Recommended Books for UPSC CSE Preparation 2025",
    description: "Curated list of best books for UPSC Civil Services — Laxmikanth Polity, Bipan Chandra History, NCERT series, Ramesh Singh Economy and more with study strategy.",
    type: "books",
    exam: "UPSC CSE",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://upsc.gov.in/",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "Online",
    downloads: 134000,
    tags: ["upsc", "books", "laxmikanth", "ncert", "study plan"],
    year: 2025,
  },
  {
    id: 14,
    title: "JEE Advanced Physics Chapterwise Previous Papers",
    description: "JEE Advanced Physics previous year questions arranged chapterwise (2010–2024) — Mechanics, Waves, Thermal, Electricity, Magnetism, Modern Physics.",
    type: "previous-papers",
    exam: "JEE Advanced",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeeadv.ac.in/pastquepa.html",
    sourceUrl: "https://jeeadv.ac.in",
    fileSize: "35 MB",
    downloads: 118000,
    tags: ["jee advanced", "physics", "chapterwise", "mechanics"],
    year: 2024,
  },
  {
    id: 15,
    title: "RRB Group D Syllabus & Selection Process 2024",
    description: "Official RRB Group D exam syllabus, CBT pattern, physical efficiency test norms, and document verification process with state-wise vacancy details.",
    type: "syllabus",
    exam: "RRB Group D",
    iconColor: "#f43f5e",
    iconBg: "rgba(244,63,94,0.12)",
    downloadUrl: "https://www.rrbcdg.gov.in/",
    sourceUrl: "https://indianrailways.gov.in",
    fileSize: "3.2 MB",
    downloads: 72000,
    tags: ["rrb", "group d", "railway", "syllabus", "physical test"],
    year: 2024,
  },
  {
    id: 16,
    title: "GATE Computer Science Video Lectures – Full Course",
    description: "Free 200+ hour GATE CS/IT video lecture series covering Data Structures, Algorithms, OS, DBMS, Networks, COA, Theory of Computation and Compiler Design.",
    type: "video-lectures",
    exam: "GATE CS",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://nptel.ac.in/",
    sourceUrl: "https://nptel.ac.in",
    fileSize: "Online",
    downloads: 95000,
    tags: ["gate", "cs", "computer science", "algorithms", "os", "dbms"],
    year: 2024,
  },
  {
    id: 17,
    title: "Current Affairs Weekly Capsule – April 2025",
    description: "Weekly current affairs capsule for quick revision — Top 50 events, one-liners, new appointments, sports results and international news.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "2 MB",
    downloads: 88000,
    tags: ["current affairs", "weekly", "capsule", "revision"],
    year: 2025,
  },
  {
    id: 18,
    title: "SSC CGL Best Books Recommended by Toppers 2025",
    description: "Toppers' booklist for SSC CGL — Arihant English, Kiran Mathematics, Lucent GK, Paramount Reasoning with chapter-wise difficulty ratings and study schedule.",
    type: "books",
    exam: "SSC CGL",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://ssc.gov.in/",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "Online",
    downloads: 63000,
    tags: ["ssc", "cgl", "books", "topper", "arihant", "kiran"],
    year: 2025,
  },
];

export const resourceCategories = [
  { id: "all", label: "All Resources", count: resourcesData.length },
  { id: "previous-papers", label: "Previous Papers", count: resourcesData.filter(r => r.type === "previous-papers").length },
  { id: "syllabus", label: "Syllabus & Pattern", count: resourcesData.filter(r => r.type === "syllabus").length },
  { id: "mock-tests", label: "Mock Tests", count: resourcesData.filter(r => r.type === "mock-tests").length },
  { id: "study-notes", label: "Study Notes", count: resourcesData.filter(r => r.type === "study-notes").length },
  { id: "books", label: "Best Books", count: resourcesData.filter(r => r.type === "books").length },
  { id: "video-lectures", label: "Video Lectures", count: resourcesData.filter(r => r.type === "video-lectures").length },
  { id: "current-affairs", label: "Current Affairs", count: resourcesData.filter(r => r.type === "current-affairs").length },
];
