export interface Resource {
  id: number;
  title: string;
  description: string;
  type: string;
  exam: string;
  iconColor: string;
  iconBg: string;
  downloadUrl: string;
  sourceUrl: string;
  fileSize: string;
  downloads: number;
  tags: string[];
  year?: number;
  featured?: boolean;
}

export const resourcesData: Resource[] = [
  {
    id: 1,
    title: "UPSC CSE Prelims Previous Year Papers 2013–2024",
    description: "Complete collection of UPSC Civil Services Preliminary Examination question papers with official answer keys. Covers General Studies Paper 1 & CSAT.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "45 MB",
    downloads: 182000,
    tags: ["upsc", "civil services", "prelims", "question papers"],
    year: 2024,
    featured: true,
  },
  {
    id: 2,
    title: "SSC CGL Complete Syllabus & Exam Pattern 2024–25",
    description: "Official SSC CGL syllabus for Tier 1, 2, 3 and 4 with topic-wise weightage, marking scheme, and exam pattern changes for 2024–25 cycle.",
    type: "syllabus",
    exam: "SSC CGL",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://ssc.gov.in/Examination/Syllabus",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "2.1 MB",
    downloads: 94000,
    tags: ["ssc", "cgl", "syllabus", "tier 1", "tier 2"],
    year: 2024,
    featured: true,
  },
  {
    id: 3,
    title: "IBPS PO Mock Test Series – 25 Full-Length Tests",
    description: "Free mock tests for IBPS PO Prelims and Mains covering Reasoning Ability, Quantitative Aptitude, English Language, General Awareness and Professional Knowledge.",
    type: "mock-tests",
    exam: "IBPS PO",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://www.ibps.in/",
    sourceUrl: "https://www.ibps.in",
    fileSize: "Online",
    downloads: 76000,
    tags: ["ibps", "po", "mock test", "banking", "prelims"],
    year: 2024,
  },
  {
    id: 4,
    title: "RRB NTPC Previous Year Papers 2016–2024",
    description: "All Railway Recruitment Board NTPC question papers from 2016 to 2024, categorised by phase and shift, with detailed solutions.",
    type: "previous-papers",
    exam: "RRB NTPC",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://www.rrbcdg.gov.in/",
    sourceUrl: "https://indianrailways.gov.in",
    fileSize: "32 MB",
    downloads: 128000,
    tags: ["rrb", "ntpc", "railway", "previous papers"],
    year: 2024,
  },
  {
    id: 5,
    title: "NEET UG Biology Notes – NCERT Topicwise",
    description: "Comprehensive NCERT-based Biology notes for NEET UG preparation covering Botany and Zoology with diagrams, mnemonics and important questions.",
    type: "study-notes",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://ncert.nic.in/textbook.php",
    sourceUrl: "https://ncert.nic.in",
    fileSize: "18 MB",
    downloads: 211000,
    tags: ["neet", "biology", "ncert", "botany", "zoology"],
    year: 2024,
    featured: true,
  },
  {
    id: 6,
    title: "JEE Main Mathematics Formula Sheet",
    description: "All essential formulas for JEE Main Mathematics — Calculus, Algebra, Trigonometry, Coordinate Geometry, Probability and Vectors in one sheet.",
    type: "study-notes",
    exam: "JEE Main",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeemain.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "5 MB",
    downloads: 163000,
    tags: ["jee", "mathematics", "formula", "calculus", "algebra"],
    year: 2024,
  },
  {
    id: 7,
    title: "SBI PO Reasoning Ability – Topic-wise Practice Sets",
    description: "600+ practice questions for SBI PO Reasoning Ability covering Puzzles, Seating Arrangement, Syllogism, Blood Relations, Coding-Decoding and more.",
    type: "mock-tests",
    exam: "SBI PO",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://sbi.co.in/web/careers",
    sourceUrl: "https://sbi.co.in",
    fileSize: "12 MB",
    downloads: 89000,
    tags: ["sbi", "po", "reasoning", "puzzles", "practice"],
    year: 2024,
  },
  {
    id: 8,
    title: "UPSC Mains GS Paper 1 – 15 Years Solved Papers",
    description: "Solved UPSC Mains General Studies Paper 1 (History, Geography, Society) from 2010 to 2024 with model answers and examiner's comments.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "28 MB",
    downloads: 97000,
    tags: ["upsc", "mains", "gs paper 1", "history", "geography"],
    year: 2024,
  },
  {
    id: 9,
    title: "SSC CHSL Syllabus & Tier-Wise Pattern 2024",
    description: "Complete SSC Combined Higher Secondary Level exam syllabus covering Tier 1 (CBT), Tier 2 (Descriptive), Tier 3 (Skill Test) with score breakdown.",
    type: "syllabus",
    exam: "SSC CHSL",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://ssc.gov.in/Examination/Syllabus",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "1.8 MB",
    downloads: 58000,
    tags: ["ssc", "chsl", "syllabus", "tier 1", "pattern"],
    year: 2024,
  },
  {
    id: 10,
    title: "IBPS Clerk Quantitative Aptitude Video Lectures",
    description: "50+ hours of free video lectures for IBPS Clerk Quantitative Aptitude covering Number System, Percentage, SI/CI, Speed-Distance-Time and Data Interpretation.",
    type: "video-lectures",
    exam: "IBPS Clerk",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://www.youtube.com/results?search_query=ibps+clerk+quantitative+aptitude",
    sourceUrl: "https://youtube.com",
    fileSize: "Online",
    downloads: 142000,
    tags: ["ibps", "clerk", "quant", "video", "number system"],
    year: 2024,
  },
  {
    id: 11,
    title: "Current Affairs Monthly Digest – March 2025",
    description: "Comprehensive monthly current affairs covering National, International, Economy, Sports, Awards, Science & Technology for all government exams.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "8 MB",
    downloads: 201000,
    tags: ["current affairs", "monthly", "national", "international", "sports"],
    year: 2025,
    featured: true,
  },
  {
    id: 12,
    title: "NEET UG Physics – 20 Years Chapterwise Questions",
    description: "Chapterwise collection of NEET Physics questions from 2005 to 2024 with step-by-step solutions, covering Mechanics, Thermodynamics, Optics, Electrodynamics.",
    type: "previous-papers",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://neet.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "22 MB",
    downloads: 176000,
    tags: ["neet", "physics", "chapterwise", "mechanics", "optics"],
    year: 2024,
  },
  {
    id: 13,
    title: "Recommended Books for UPSC CSE Preparation 2025",
    description: "Curated list of best books for UPSC Civil Services — Laxmikanth Polity, Bipan Chandra History, NCERT series, Ramesh Singh Economy and more with study strategy.",
    type: "books",
    exam: "UPSC CSE",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://upsc.gov.in/",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "Online",
    downloads: 134000,
    tags: ["upsc", "books", "laxmikanth", "ncert", "study plan"],
    year: 2025,
  },
  {
    id: 14,
    title: "JEE Advanced Physics Chapterwise Previous Papers",
    description: "JEE Advanced Physics previous year questions arranged chapterwise (2010–2024) — Mechanics, Waves, Thermal, Electricity, Magnetism, Modern Physics.",
    type: "previous-papers",
    exam: "JEE Advanced",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeeadv.ac.in/pastquepa.html",
    sourceUrl: "https://jeeadv.ac.in",
    fileSize: "35 MB",
    downloads: 118000,
    tags: ["jee advanced", "physics", "chapterwise", "mechanics"],
    year: 2024,
  },
  {
    id: 15,
    title: "RRB Group D Syllabus & Selection Process 2024",
    description: "Official RRB Group D exam syllabus, CBT pattern, physical efficiency test norms, and document verification process with state-wise vacancy details.",
    type: "syllabus",
    exam: "RRB Group D",
    iconColor: "#f43f5e",
    iconBg: "rgba(244,63,94,0.12)",
    downloadUrl: "https://www.rrbcdg.gov.in/",
    sourceUrl: "https://indianrailways.gov.in",
    fileSize: "3.2 MB",
    downloads: 72000,
    tags: ["rrb", "group d", "railway", "syllabus", "physical test"],
    year: 2024,
  },
  {
    id: 16,
    title: "GATE Computer Science Video Lectures – Full Course",
    description: "Free 200+ hour GATE CS/IT video lecture series covering Data Structures, Algorithms, OS, DBMS, Networks, COA, Theory of Computation and Compiler Design.",
    type: "video-lectures",
    exam: "GATE CS",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://nptel.ac.in/",
    sourceUrl: "https://nptel.ac.in",
    fileSize: "Online",
    downloads: 95000,
    tags: ["gate", "cs", "computer science", "algorithms", "os", "dbms"],
    year: 2024,
  },
  {
    id: 17,
    title: "Current Affairs Weekly Capsule – April 2025",
    description: "Weekly current affairs capsule for quick revision — Top 50 events, one-liners, new appointments, sports results and international news.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "2 MB",
    downloads: 88000,
    tags: ["current affairs", "weekly", "capsule", "revision"],
    year: 2025,
  },
  {
    id: 18,
    title: "SSC CGL Best Books Recommended by Toppers 2025",
    description: "Toppers' booklist for SSC CGL — Arihant English, Kiran Mathematics, Lucent GK, Paramount Reasoning with chapter-wise difficulty ratings and study schedule.",
    type: "books",
    exam: "SSC CGL",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://ssc.gov.in/",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "Online",
    downloads: 63000,
    tags: ["ssc", "cgl", "books", "topper", "arihant", "kiran"],
    year: 2025,
  },
  {
    id: 19,
    title: "UPSC CSE Mains GS Paper 2 – Polity & Governance Solved",
    description: "15 years solved UPSC Mains GS2 papers (Polity, Constitution, Governance, Social Justice, International Relations) with comprehensive model answers.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "24 MB",
    downloads: 82000,
    tags: ["upsc", "mains", "gs paper 2", "polity", "governance"],
    year: 2024,
  },
  {
    id: 20,
    title: "NEET UG Chemistry – Inorganic & Organic Formula Charts",
    description: "Visual formula charts and reaction summaries for NEET Chemistry — Periodic Trends, Named Reactions, Coordination Compounds, and Biomolecules.",
    type: "study-notes",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://ncert.nic.in/textbook.php",
    sourceUrl: "https://ncert.nic.in",
    fileSize: "7 MB",
    downloads: 144000,
    tags: ["neet", "chemistry", "inorganic", "organic", "reaction"],
    year: 2024,
  },
  {
    id: 21,
    title: "IBPS RRB Officer Scale-I Previous Papers 2017–2024",
    description: "Previous year papers for IBPS RRB Officer Scale-I Prelims and Mains from 2017 to 2024 with complete solutions and section-wise analysis.",
    type: "previous-papers",
    exam: "IBPS RRB",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://www.ibps.in/",
    sourceUrl: "https://www.ibps.in",
    fileSize: "28 MB",
    downloads: 67000,
    tags: ["ibps", "rrb", "officer scale", "rural bank", "previous papers"],
    year: 2024,
  },
  {
    id: 22,
    title: "UPSC IAS Essay Paper – 25 Years Collection with Analysis",
    description: "All UPSC Essay papers from 2000 to 2024 with topic analysis, best essays by toppers, frequency trends, and writing strategies for Section A & B.",
    type: "previous-papers",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "15 MB",
    downloads: 71000,
    tags: ["upsc", "essay", "mains", "writing", "strategy"],
    year: 2024,
  },
  {
    id: 23,
    title: "SSC MTS Syllabus, Exam Pattern & Eligibility 2024",
    description: "Complete SSC Multi-Tasking Staff exam syllabus with CBT (Paper 1) and Paper 2 (Descriptive) pattern, eligibility criteria, and selection procedure.",
    type: "syllabus",
    exam: "SSC MTS",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://ssc.gov.in/Examination/Syllabus",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "1.5 MB",
    downloads: 43000,
    tags: ["ssc", "mts", "syllabus", "multi tasking staff"],
    year: 2024,
  },
  {
    id: 24,
    title: "JEE Main Chemistry NCERT-Based Notes (Class 11 & 12)",
    description: "Concise, exam-focused chemistry notes for JEE Main covering all chapters from NCERT Class 11 and 12 with important reactions and exceptions.",
    type: "study-notes",
    exam: "JEE Main",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeemain.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "12 MB",
    downloads: 98000,
    tags: ["jee", "chemistry", "ncert", "class 11", "class 12"],
    year: 2024,
  },
  {
    id: 25,
    title: "RRB JE CBT-1 Syllabus & Study Plan 2024",
    description: "Complete RRB Junior Engineer CBT-1 syllabus covering Mathematics, General Intelligence, General Awareness and General Science with 60-day study plan.",
    type: "syllabus",
    exam: "RRB JE",
    iconColor: "#f43f5e",
    iconBg: "rgba(244,63,94,0.12)",
    downloadUrl: "https://www.rrbcdg.gov.in/",
    sourceUrl: "https://indianrailways.gov.in",
    fileSize: "2.8 MB",
    downloads: 51000,
    tags: ["rrb", "junior engineer", "je", "syllabus", "cbt"],
    year: 2024,
  },
  {
    id: 26,
    title: "SBI Clerk (Junior Associates) Mock Tests – 30 Sets",
    description: "30 full-length SBI Junior Associates mock tests for Prelims and Mains with section-wise timer, detailed solutions and performance analytics.",
    type: "mock-tests",
    exam: "SBI Clerk",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://sbi.co.in/web/careers",
    sourceUrl: "https://sbi.co.in",
    fileSize: "Online",
    downloads: 57000,
    tags: ["sbi", "clerk", "junior associates", "mock test", "prelims"],
    year: 2024,
  },
  {
    id: 27,
    title: "GATE Electrical Engineering Video Lectures – NPTEL",
    description: "Complete NPTEL video lecture series for GATE EE covering Electric Circuits, Machines, Power Systems, Control Systems, Signals & Systems, EMT.",
    type: "video-lectures",
    exam: "GATE EE",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://nptel.ac.in/",
    sourceUrl: "https://nptel.ac.in",
    fileSize: "Online",
    downloads: 48000,
    tags: ["gate", "electrical", "ee", "nptel", "power systems"],
    year: 2024,
  },
  {
    id: 28,
    title: "Current Affairs January–March 2025 Quarterly Digest",
    description: "Complete Q1 2025 current affairs covering Budget 2025, state elections, defence deals, science launches, sports results and international diplomacy.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "11 MB",
    downloads: 112000,
    tags: ["current affairs", "quarterly", "budget 2025", "january", "march"],
    year: 2025,
  },
  {
    id: 29,
    title: "NEET PG Preparation Best Books & Study Strategy 2025",
    description: "Top books for NEET PG — Harrison's Internal Medicine, Robbins Pathology, KD Tripathi Pharmacology, Manson's Parasitology with subject-wise priority list.",
    type: "books",
    exam: "NEET PG",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://nbe.edu.in/",
    sourceUrl: "https://nbe.edu.in",
    fileSize: "Online",
    downloads: 38000,
    tags: ["neet pg", "medical", "books", "harrison", "robbins"],
    year: 2025,
  },
  {
    id: 30,
    title: "Defence Exams Best Books – CDS, AFCAT, NDA 2025",
    description: "Complete booklist for defence exams — Pathfinder CDS, AFCAT Success Package, NDA & NA by R Gupta with chapter-wise topic coverage.",
    type: "books",
    exam: "CDS / AFCAT / NDA",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://www.joinindianarmy.nic.in/",
    sourceUrl: "https://www.joinindianarmy.nic.in",
    fileSize: "Online",
    downloads: 29000,
    tags: ["cds", "afcat", "nda", "defence", "books"],
    year: 2025,
  },
  {
    id: 31,
    title: "NDA & NA Previous Year Papers 2015–2024",
    description: "Complete NDA and NA Exam I & II question papers from 2015 to 2024 with solutions for Mathematics, General Ability Test (GAT) covering all sections.",
    type: "previous-papers",
    exam: "NDA",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "26 MB",
    downloads: 54000,
    tags: ["nda", "na", "defence", "mathematics", "gat"],
    year: 2024,
  },
  {
    id: 32,
    title: "CUET UG Syllabus & Sample Papers – All Subjects 2025",
    description: "CUET UG 2025 syllabus, sample question papers and marking scheme for all 27 domain subjects plus Language Test and General Test.",
    type: "syllabus",
    exam: "CUET UG",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://cuet.samarth.ac.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "4.5 MB",
    downloads: 46000,
    tags: ["cuet", "ug", "nta", "syllabus", "sample papers"],
    year: 2025,
  },
  {
    id: 33,
    title: "UPSC Prelims GS Paper 1 Mock Test Series – 40 Tests",
    description: "40 full-length UPSC Prelims GS Paper 1 mock tests with topics from History, Polity, Geography, Economy, Environment and Current Affairs, with solutions.",
    type: "mock-tests",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "Online",
    downloads: 93000,
    tags: ["upsc", "mock test", "prelims", "gs paper 1", "full length"],
    year: 2024,
    featured: true,
  },
  {
    id: 34,
    title: "IBPS SO (Specialist Officer) Syllabus & Pattern 2024",
    description: "Complete IBPS Specialist Officer syllabus for IT, HR, Law, Agriculture, Rajbhasha Adhikari — Prelims and Mains with professional knowledge topics.",
    type: "syllabus",
    exam: "IBPS SO",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://www.ibps.in/",
    sourceUrl: "https://www.ibps.in",
    fileSize: "2.3 MB",
    downloads: 31000,
    tags: ["ibps", "specialist officer", "so", "it officer", "syllabus"],
    year: 2024,
  },
  {
    id: 35,
    title: "JEE Advanced 20 Years Chemistry Previous Papers",
    description: "Complete JEE Advanced Chemistry question bank (2004–2024), chapterwise and yearwise, with detailed solutions covering all reaction mechanisms and concepts.",
    type: "previous-papers",
    exam: "JEE Advanced",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeeadv.ac.in/pastquepa.html",
    sourceUrl: "https://jeeadv.ac.in",
    fileSize: "30 MB",
    downloads: 87000,
    tags: ["jee advanced", "chemistry", "previous papers", "organic", "inorganic"],
    year: 2024,
  },
  {
    id: 36,
    title: "UPSC Indian Forest Service Syllabus 2024",
    description: "Official IFS syllabus for Preliminary (GS + Aptitude) and Mains (optional subjects: Agriculture, Botany, Chemistry, Physics, Zoology, Forestry, etc.).",
    type: "syllabus",
    exam: "UPSC IFS",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/syllabus-mat",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "3.1 MB",
    downloads: 22000,
    tags: ["upsc", "ifs", "forest service", "syllabus", "optional"],
    year: 2024,
  },
  {
    id: 37,
    title: "GATE Mechanical Engineering Video Course – NPTEL",
    description: "Free NPTEL video lectures for GATE ME — Thermodynamics, Fluid Mechanics, Manufacturing, Strength of Materials, Machine Design, Heat Transfer.",
    type: "video-lectures",
    exam: "GATE ME",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://nptel.ac.in/",
    sourceUrl: "https://nptel.ac.in",
    fileSize: "Online",
    downloads: 52000,
    tags: ["gate", "mechanical", "me", "nptel", "thermodynamics"],
    year: 2024,
  },
  {
    id: 38,
    title: "Current Affairs 2024 Annual Yearbook – Complete Edition",
    description: "Full-year 2024 current affairs compilation for competitive exams — 12-month highlights, important GK facts, one-liners, and exam-specific capsules.",
    type: "current-affairs",
    exam: "All Exams",
    iconColor: "#10b981",
    iconBg: "rgba(16,185,129,0.12)",
    downloadUrl: "https://pib.gov.in/",
    sourceUrl: "https://pib.gov.in",
    fileSize: "22 MB",
    downloads: 198000,
    tags: ["current affairs", "2024", "annual", "yearbook", "gk"],
    year: 2025,
    featured: true,
  },
  {
    id: 39,
    title: "SSC JHT Syllabus, Pattern & Previous Papers 2024",
    description: "SSC Junior Hindi Translator exam syllabus, question paper pattern, eligibility requirements and previous year papers with answer keys.",
    type: "syllabus",
    exam: "SSC JHT",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://ssc.gov.in/",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "1.9 MB",
    downloads: 18000,
    tags: ["ssc", "jht", "hindi translator", "syllabus", "translation"],
    year: 2024,
  },
  {
    id: 40,
    title: "UPSC CSAT Paper 2 – Aptitude Practice Questions 2024",
    description: "1000+ CSAT practice questions for Comprehension, Reasoning, Analytical Ability, Decision Making and Basic Numeracy with difficulty ratings.",
    type: "mock-tests",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "Online",
    downloads: 74000,
    tags: ["upsc", "csat", "aptitude", "reasoning", "comprehension"],
    year: 2024,
  },
  {
    id: 41,
    title: "JEE Main Physics – Chapter-wise DPPs (Daily Practice)",
    description: "700+ Daily Practice Problems for JEE Main Physics arranged chapter-wise from Mechanics to Modern Physics with hints and solutions for each set.",
    type: "study-notes",
    exam: "JEE Main",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://jeemain.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "16 MB",
    downloads: 109000,
    tags: ["jee", "physics", "dpp", "practice problems", "mechanics"],
    year: 2024,
  },
  {
    id: 42,
    title: "NEET UG Revision Notes – All Subjects Quick Recap",
    description: "Last-minute revision notes for NEET covering all three subjects — Physics, Chemistry and Biology — in concise bullet-point format for quick recall.",
    type: "study-notes",
    exam: "NEET UG",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://neet.nta.nic.in/",
    sourceUrl: "https://nta.ac.in",
    fileSize: "9 MB",
    downloads: 187000,
    tags: ["neet", "revision", "all subjects", "quick recap", "last minute"],
    year: 2024,
  },
  {
    id: 43,
    title: "Bihar BPSC Previous Year Papers 2016–2024",
    description: "Bihar Public Service Commission (BPSC) Prelims and Mains previous year question papers from 2016 to 2024 with solutions and trend analysis.",
    type: "previous-papers",
    exam: "BPSC",
    iconColor: "#f43f5e",
    iconBg: "rgba(244,63,94,0.12)",
    downloadUrl: "https://www.bpsc.bih.nic.in/",
    sourceUrl: "https://www.bpsc.bih.nic.in",
    fileSize: "20 MB",
    downloads: 41000,
    tags: ["bpsc", "bihar psc", "state psc", "previous papers", "prelims"],
    year: 2024,
  },
  {
    id: 44,
    title: "Rajasthan RPSC RAS Syllabus & Previous Papers 2024",
    description: "Complete RPSC RAS/RTS Combined Competitive Exam syllabus for Prelims and Mains with Rajasthan-specific GK topics and previous year papers.",
    type: "syllabus",
    exam: "RPSC RAS",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://rpsc.rajasthan.gov.in/",
    sourceUrl: "https://rpsc.rajasthan.gov.in",
    fileSize: "4.2 MB",
    downloads: 35000,
    tags: ["rpsc", "ras", "rajasthan psc", "state exam", "syllabus"],
    year: 2024,
  },
  {
    id: 45,
    title: "GATE Civil Engineering – Previous Papers 2014–2024",
    description: "All GATE Civil Engineering question papers from 2014 to 2024 with detailed solutions covering Structural Engineering, Geotechnical, Hydraulics, and Transportation.",
    type: "previous-papers",
    exam: "GATE CE",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://gate2024.iisc.ac.in/",
    sourceUrl: "https://gate.iitk.ac.in",
    fileSize: "19 MB",
    downloads: 44000,
    tags: ["gate", "civil engineering", "ce", "previous papers", "structural"],
    year: 2024,
  },
  {
    id: 46,
    title: "UP Police Constable Syllabus & Exam Pattern 2024",
    description: "Complete UP Police Constable exam syllabus, CBT pattern, physical test standards, PMT/PST requirements and district-wise vacancy details.",
    type: "syllabus",
    exam: "UP Police",
    iconColor: "#f43f5e",
    iconBg: "rgba(244,63,94,0.12)",
    downloadUrl: "https://uppbpb.gov.in/",
    sourceUrl: "https://uppbpb.gov.in",
    fileSize: "2.6 MB",
    downloads: 62000,
    tags: ["up police", "constable", "syllabus", "state police", "physical test"],
    year: 2024,
  },
  {
    id: 47,
    title: "MPSC State Services Syllabus & Previous Papers 2024",
    description: "Maharashtra Public Service Commission State Services exam complete syllabus for Prelims and Mains with Maharashtra-specific topics and solved papers.",
    type: "syllabus",
    exam: "MPSC",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://mpsc.gov.in/",
    sourceUrl: "https://mpsc.gov.in",
    fileSize: "3.8 MB",
    downloads: 29000,
    tags: ["mpsc", "maharashtra psc", "state exam", "syllabus"],
    year: 2024,
  },
  {
    id: 48,
    title: "GATE Electronics & Communication Video Lectures",
    description: "Free NPTEL GATE ECE video lectures covering Analog Circuits, Digital Electronics, Communications, Signals & Systems, EM Theory and Control Systems.",
    type: "video-lectures",
    exam: "GATE ECE",
    iconColor: "#6366f1",
    iconBg: "rgba(99,102,241,0.12)",
    downloadUrl: "https://nptel.ac.in/",
    sourceUrl: "https://nptel.ac.in",
    fileSize: "Online",
    downloads: 41000,
    tags: ["gate", "ece", "electronics", "nptel", "signals"],
    year: 2024,
  },
  {
    id: 49,
    title: "UPSC Ethics Paper IV – Answer Writing Practice Guide",
    description: "Comprehensive practice guide for UPSC Mains GS Paper 4 (Ethics, Integrity, Aptitude) with 200+ case studies, model answers and thinkers' summaries.",
    type: "study-notes",
    exam: "UPSC CSE",
    iconColor: "#3b82f6",
    iconBg: "rgba(59,130,246,0.12)",
    downloadUrl: "https://upsc.gov.in/",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "14 MB",
    downloads: 76000,
    tags: ["upsc", "ethics", "gs paper 4", "integrity", "case studies"],
    year: 2024,
  },
  {
    id: 50,
    title: "SSC CPO Sub Inspector Syllabus & Selection 2024",
    description: "Complete SSC Central Police Organisation (CPO) exam syllabus for SI in Delhi Police and CAPFs — Paper I, Paper II, PET/PST and DV details.",
    type: "syllabus",
    exam: "SSC CPO",
    iconColor: "#ec4899",
    iconBg: "rgba(236,72,153,0.12)",
    downloadUrl: "https://ssc.gov.in/",
    sourceUrl: "https://ssc.gov.in",
    fileSize: "2.4 MB",
    downloads: 36000,
    tags: ["ssc", "cpo", "sub inspector", "delhi police", "capf"],
    year: 2024,
  },
  {
    id: 51,
    title: "CDS Combined Defence Services Previous Papers 2014–2024",
    description: "All CDS I & II question papers from 2014 to 2024 with solutions for English, General Knowledge, and Mathematics sections with section-wise analysis.",
    type: "previous-papers",
    exam: "CDS",
    iconColor: "#f97316",
    iconBg: "rgba(249,115,22,0.12)",
    downloadUrl: "https://upsc.gov.in/examinations/previous-question-papers",
    sourceUrl: "https://upsc.gov.in",
    fileSize: "24 MB",
    downloads: 48000,
    tags: ["cds", "defence", "combined defence", "english", "gk"],
    year: 2024,
  },
  {
    id: 52,
    title: "UGC NET Paper 1 – 10 Years Previous Papers & Solutions",
    description: "UGC NET Paper 1 (Teaching & Research Aptitude) previous 10 years question papers with detailed solutions, topic analysis and high-weightage areas.",
    type: "previous-papers",
    exam: "UGC NET",
    iconColor: "#14b8a6",
    iconBg: "rgba(20,184,166,0.12)",
    downloadUrl: "https://ugcnet.nta.nic.in/",
    sourceUrl: "https://ugcnet.nta.nic.in",
    fileSize: "17 MB",
    downloads: 52000,
    tags: ["ugc net", "paper 1", "teaching aptitude", "research", "previous papers"],
    year: 2024,
  },
  {
    id: 53,
    title: "CLAT Previous Papers 2010–2024 – Law Entrance",
    description: "Complete CLAT (Common Law Admission Test) question papers from 2010 to 2024 for NLU admissions with section analysis for English, GK, Legal Reasoning.",
    type: "previous-papers",
    exam: "CLAT",
    iconColor: "#8b5cf6",
    iconBg: "rgba(139,92,246,0.12)",
    downloadUrl: "https://consortiumofnlus.ac.in/",
    sourceUrl: "https://consortiumofnlus.ac.in",
    fileSize: "13 MB",
    downloads: 34000,
    tags: ["clat", "law entrance", "nlu", "legal reasoning", "previous papers"],
    year: 2024,
  },
  {
    id: 54,
    title: "CAT Previous Year Papers 2017–2024 with Analysis",
    description: "IIM CAT question papers from 2017 to 2024 covering VARC, DILR, and QA sections with detailed solutions, difficulty levels and percentile cutoff data.",
    type: "previous-papers",
    exam: "CAT",
    iconColor: "#eab308",
    iconBg: "rgba(234,179,8,0.12)",
    downloadUrl: "https://iimcat.ac.in/",
    sourceUrl: "https://iimcat.ac.in",
    fileSize: "18 MB",
    downloads: 79000,
    tags: ["cat", "iim", "mba", "varc", "dilr", "quant"],
    year: 2024,
  },
];

export const resourceCategories = [
  { id: "all", label: "All Resources", count: resourcesData.length },
  { id: "previous-papers", label: "Previous Papers", count: resourcesData.filter(r => r.type === "previous-papers").length },
  { id: "syllabus", label: "Syllabus & Pattern", count: resourcesData.filter(r => r.type === "syllabus").length },
  { id: "mock-tests", label: "Mock Tests", count: resourcesData.filter(r => r.type === "mock-tests").length },
  { id: "study-notes", label: "Study Notes", count: resourcesData.filter(r => r.type === "study-notes").length },
  { id: "books", label: "Best Books", count: resourcesData.filter(r => r.type === "books").length },
  { id: "video-lectures", label: "Video Lectures", count: resourcesData.filter(r => r.type === "video-lectures").length },
  { id: "current-affairs", label: "Current Affairs", count: resourcesData.filter(r => r.type === "current-affairs").length },
];
